routes/web.php
<?php

use App\Http\Controllers\ContactUsFormController;
use App\Http\Controllers\ContactUsListController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/masuk', [HomeController::class, 'masuk']);
Route::get('/contactUs', [HomeController::class, 'contactUs']);


Route::get('/contact',[ContactUsFormController::class, 'create']);
Route::post('/contact',[ContactUsFormController::class, 'store'])->name('contact.store');

// Route::get('/contact-list',[ContactUsListController::class, 'index']);
// Route::put('/contact-list/{id}',[ContactUsListController::class, 'edit'])->name('contact.edit');

Route::resource('/contact-list',ContactUsListController::class);
Route::put('/update-list',[ContactUsListController::class, 'updateList'])->name('update-list');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
    public $fillable = [
        'name', 
        'email', 
        'phone', 
        'subject', 
        'message'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactUsFormController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactUsFormController extends Controller
{
    public function create() {
        return view('contact');
    }

    public function store(Request $request) {
        $this->validate($request,[
            'name' => 'required',
            'email' => 'required|email',
            'phone' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
            'subject'=>'required',
            'message' => 'required'
        ]);

        Contact::create($request->all());

        return back()->with('Berhasil','Pesan anda telah terkirim');
    }
}

app/Http/Controllers/ContactUsListController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactUsListController extends Controller
{
    public function index()
    {
        $contacts = Contact::all();
        return view('contact-list', compact('contacts', 'contacts'));
    }
    public function show()
    {
        $contacts = Contact::all();
        return view('contact-list', compact('contacts', 'contacts'));
    }

    public function edit($id)
    {
        $contact = Contact::find($id);
        return view('message-edit', compact('contact'));
    }

    public function update(Request $request)
    {
        //code..
    }

    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();
        return redirect('/contact-list')->with('success', 'List deleted successfully');
    }

    public function updateList(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'phone' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
            'subject' => 'required',
            'message' => 'required'
        ]);

        $contact = Contact::find($request->get('id'));
        $contact->name = $request->get('name');
        $contact->email = $request->get('email');
        $contact->phone = $request->get('phone');
        $contact->subject = $request->get('subject');
        $contact->message = $request->get('message');
        $contact->save();
        return redirect('/contact-list')->with('success', 'List Updated successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    public function masuk()
    {
        return view('login');
    }
    public function contactUs()
    {
        return view('contact');
    }
}

resources/views/contact-list.blade.php
@extends('layout.main')

@section('css')
    <link rel="stylesheet" href="{{ URL::asset('css/contact-list.css') }}">
@endsection

@section('content')
    <div class="page-title">
        <h2>List Pesan</h2>
    </div>
    <table class="styled-table">
        <thead>
            <tr>
                <th>Nama</th>
                <th>Email</th>
                <th>No. Telepon</th>
                <th>Subject</th>
                <th>Pesan</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach ($contacts as $contact)
                <tr>
                    <td>{{ $contact->name }}</td>
                    <td>{{ $contact->email }}</td>
                    <td>{{ $contact->phone }}</td>
                    <td>{{ $contact->subject }}</td>
                    <td>{{ $contact->message }}</td>
                    <td>
                        <form action="{{ route('contact-list.destroy', $contact->id) }}" method="POST">
                            <a class="btn btn-primary" href="{{ route('contact-list.edit', $contact->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/contact.blade.php
@extends('layout.main')
@section('css')
    <link rel="stylesheet" href="{{ URL::asset('css/contact-page.css') }}">
@endsection

@section('content')
    <div class="container">
        <form action="{{ route('contact.store') }}" method="POST">
            <div >
                @if ($errors->any())
                    <div class="alert">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }} </li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
            @csrf
            <br>
            <label>Nama</label>
            <input class="input-text" type="text" id="name" name="name" placeholder="Your name..">

            <label>Email</label>
            <input class="input-text" type="email" id="email" name="email" placeholder="Your email.." required>

            <label>No. Telepon</label>
            <input class="input-text" type="text" id="phone" name="phone" placeholder="Your Phone Number.." required>

            <label>Subject</label>
            <input class="input-text" type="text" id="subject" name="subject" placeholder="Write Subject.." required>

            <label>Pesan</label>
            <textarea class="input-text" id="message" name="message" placeholder="Write something.." style="height:200px"
                required></textarea>

            <input type="submit" value="Submit" name="send">

        </form>
    </div>
@endsection

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ URL::asset('css/landing-page.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @yield('css')
</head>

<body>
    <!-- Navbar -->
    @include('components.navbar')

    <!-- Konten --->
    @yield('content')

    <!-- Footer --->
    <footer class="f-con">
      @include('components.footer')

    </footer>
    <script src="{{ asset('js/landing-page.js') }}"></script>
</body>

</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{{ URL::asset('css/login.css') }}">
</head>

<body>
  <h2 class="page-title">Masuk ke Investree</h2>
<div class="container">
  <form action="/action_page.php" method="post">
    <div class="imgcontainer">
      <img src="https://investree.id/v3/1647494991991/img/inv_logo.55026ac7.png" alt="Avatar">
    </div>

    <div class="container">
      <label for="username"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="username" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <button type="submit">Login</button>
      <label>
        <input type="checkbox" checked="checked" name="remember"> Remember me
      </label>
    </div>
  </form>
</div>
  



</body>

</html>

resources/views/message-edit.blade.php
@extends('layout.main')
@section('css')
    <link rel="stylesheet" href="{{ URL::asset('css/contact-page.css') }}">
@endsection

@section('content')
    <div class="container">
        <form action="{{ route('update-list') }}" method="POST">
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }} </li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>

            @csrf
            @method('PUT')
            <input hidden name="id" value="{{ $contact->id }}">
            <br>
            <label>Nama</label>
            <input class="input-text" type="text" id="name" name="name" value="{{ $contact->name }}" required>

            <label>Email</label>
            <input class="input-text" type="email" id="email" name="email" value="{{ $contact->email }}" required>

            <label>No. Telepon</label>
            <input class="input-text" type="text" id="phone" name="phone" value="{{ $contact->phone }}" required>

            <label>Subject</label>
            <input class="input-text" type="text" id="subject" name="subject" value="{{ $contact->subject }}" required>

            <label>Pesan</label>
            <textarea class="input-text" id="message" name="message" value="{{ $contact->message }}" style="height:200px"
                required>{{ $contact->message }}</textarea>

            <input type="submit" value="Submit" name="send">

        </form>
    </div>
@endsection